# Generated by Django 5.2.3 on 2025-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cashier', 'Cashier'), ('warehouse_manager', 'Warehouse Manager'), ('delivery_boy', 'Delivery Boy'), ('cse', 'Customer Service Executive'), ('gm', 'General Manager')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='users.role'),
        ),
    ]
