# Generated by Django 5.2.3 on 2025-06-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_item_vehicle_warehouse_remove_order_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.warehouse'),
        ),
    ]
