# Generated by Django 5.2.3 on 2025-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
