# Generated by Django 5.2.3 on 2025-06-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_warehouse_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='stock',
        ),
    ]
